type=Type
creation=Creation time
number=Number
age=Age
isFruiting=Is Fruiting
theGarden=The Garden
tree=Tree
transplant=is being transplanted
notTransplant=does not need to be transplanted yet
