.SUFFIXES: .class .java

PACK=main
TARG=main
JC=javac -g -encoding utf8
JM=java -ea -jar
JR=jar -cfe

OBJ=$(PACK)\Text.class \
    $(PACK)\Main.class

.java.class:
	$(JC) $<

run: build
	$(JM) $(TARG).jar

build: 	$(OBJ)
	$(JR) $(TARG).jar $(PACK).Main $(OBJ)

clean:
	for %%f in ($(OBJ)) do del %%f
	del $(TARG).jar
