// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(RosterContext))]
    [Migration("20250406092258_Procedures")]
    partial class Procedures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Roster", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<short>("Jersey")
                        .HasColumnType("smallint");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Weight")
                        .HasColumnType("smallint");

                    b.HasKey("PlayerId");

                    b.ToTable("Rosters");

                    b.HasData(
                        new
                        {
                            PlayerId = "adamlem",
                            BirthCity = "Stamford",
                            BirthState = "CT",
                            Birthday = new DateTime(2001, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Mike",
                            Height = (short)197,
                            Jersey = (short)12,
                            Position = "RW",
                            Sname = "Adamle",
                            Weight = (short)73
                        },
                        new
                        {
                            PlayerId = "adamles",
                            BirthCity = "Columbus",
                            BirthState = "OH",
                            Birthday = new DateTime(1999, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Scott",
                            Height = (short)184,
                            Jersey = (short)17,
                            Position = "D",
                            Sname = "Adamle",
                            Weight = (short)70
                        },
                        new
                        {
                            PlayerId = "armanova",
                            BirthCity = "Minsk",
                            BirthState = "RU",
                            Birthday = new DateTime(1998, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Arkady",
                            Height = (short)197,
                            Jersey = (short)31,
                            Position = "LW",
                            Sname = "Armanov",
                            Weight = (short)71
                        },
                        new
                        {
                            PlayerId = "boolea",
                            BirthCity = "Kiev",
                            BirthState = "UK",
                            Birthday = new DateTime(1997, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Alexi",
                            Height = (short)194,
                            Jersey = (short)8,
                            Position = "RW",
                            Sname = "Boole",
                            Weight = (short)72
                        },
                        new
                        {
                            PlayerId = "choakd",
                            BirthCity = "Prague",
                            BirthState = "CZ",
                            Birthday = new DateTime(1997, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Dominick",
                            Height = (short)196,
                            Jersey = (short)11,
                            Position = "RW",
                            Sname = "Choak",
                            Weight = (short)72
                        },
                        new
                        {
                            PlayerId = "clobberk",
                            BirthCity = "Bangor",
                            BirthState = "ME",
                            Birthday = new DateTime(2002, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Kilroy",
                            Height = (short)200,
                            Jersey = (short)24,
                            Position = "D",
                            Sname = "Clobber",
                            Weight = (short)73
                        },
                        new
                        {
                            PlayerId = "clubbes",
                            BirthCity = "Paramus",
                            BirthState = "NJ",
                            Birthday = new DateTime(1999, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Sam",
                            Height = (short)190,
                            Jersey = (short)7,
                            Position = "LW",
                            Sname = "Clubbe",
                            Weight = (short)75
                        },
                        new
                        {
                            PlayerId = "finleyp",
                            BirthCity = "Denver",
                            BirthState = "CO",
                            Birthday = new DateTime(1987, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Peter",
                            Height = (short)194,
                            Jersey = (short)14,
                            Position = "D",
                            Sname = "Finley",
                            Weight = (short)76
                        },
                        new
                        {
                            PlayerId = "fiskj",
                            BirthCity = "Helsinki",
                            BirthState = "FI",
                            Birthday = new DateTime(2001, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Jerke",
                            Height = (short)193,
                            Jersey = (short)25,
                            Position = "D",
                            Sname = "Fisk",
                            Weight = (short)71
                        },
                        new
                        {
                            PlayerId = "gruberh",
                            BirthCity = "Munich",
                            BirthState = "DE",
                            Birthday = new DateTime(1991, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Hans",
                            Height = (short)175,
                            Jersey = (short)29,
                            Position = "D",
                            Sname = "Gruber",
                            Weight = (short)70
                        },
                        new
                        {
                            PlayerId = "grunwala",
                            BirthCity = "Buffalo",
                            BirthState = "NY",
                            Birthday = new DateTime(1990, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Allan",
                            Height = (short)189,
                            Jersey = (short)6,
                            Position = "C",
                            Sname = "Grunwald",
                            Weight = (short)74
                        },
                        new
                        {
                            PlayerId = "ivanovv",
                            BirthCity = "Moscow",
                            BirthState = "RU",
                            Birthday = new DateTime(2004, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Valerei",
                            Height = (short)175,
                            Jersey = (short)4,
                            Position = "C",
                            Sname = "Ivanovich",
                            Weight = (short)72
                        },
                        new
                        {
                            PlayerId = "jeffriea",
                            BirthCity = "Springfield",
                            BirthState = "MA",
                            Birthday = new DateTime(1995, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Angus",
                            Height = (short)185,
                            Jersey = (short)30,
                            Position = "G",
                            Sname = "Jeffries",
                            Weight = (short)70
                        },
                        new
                        {
                            PlayerId = "jonesr",
                            BirthCity = "Hartford",
                            BirthState = "CT",
                            Birthday = new DateTime(1997, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Robert",
                            Height = (short)189,
                            Jersey = (short)35,
                            Position = "C",
                            Sname = "Jones",
                            Weight = (short)73
                        },
                        new
                        {
                            PlayerId = "lexourb",
                            BirthCity = "Quincy",
                            BirthState = "IL",
                            Birthday = new DateTime(2001, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Bruce",
                            Height = (short)198,
                            Jersey = (short)9,
                            Position = "D",
                            Sname = "Lexour",
                            Weight = (short)75
                        },
                        new
                        {
                            PlayerId = "lunds",
                            BirthCity = "St. Paul",
                            BirthState = "MN",
                            Birthday = new DateTime(1997, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Steven",
                            Height = (short)193,
                            Jersey = (short)93,
                            Position = "D",
                            Sname = "Lund",
                            Weight = (short)71
                        },
                        new
                        {
                            PlayerId = "maguirea",
                            BirthCity = "Detroit",
                            BirthState = "MI",
                            Birthday = new DateTime(1999, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Andre",
                            Height = (short)191,
                            Jersey = (short)34,
                            Position = "LW",
                            Sname = "Maguire",
                            Weight = (short)75
                        },
                        new
                        {
                            PlayerId = "meyersd",
                            BirthCity = "Chicago",
                            BirthState = "IL",
                            Birthday = new DateTime(1998, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Doug",
                            Height = (short)195,
                            Jersey = (short)28,
                            Position = "G",
                            Sname = "Meyers",
                            Weight = (short)70
                        },
                        new
                        {
                            PlayerId = "olsens",
                            BirthCity = "Stockholm",
                            BirthState = "SW",
                            Birthday = new DateTime(1999, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Sandish",
                            Height = (short)192,
                            Jersey = (short)37,
                            Position = "D",
                            Sname = "Olsen",
                            Weight = (short)72
                        },
                        new
                        {
                            PlayerId = "quivep",
                            BirthCity = "Quebec",
                            BirthState = "QU",
                            Birthday = new DateTime(1991, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Pierre",
                            Height = (short)197,
                            Jersey = (short)20,
                            Position = "LW",
                            Sname = "Quive",
                            Weight = (short)71
                        },
                        new
                        {
                            PlayerId = "springej",
                            BirthCity = "Toronto",
                            BirthState = "ON",
                            Birthday = new DateTime(1995, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Junior",
                            Height = (short)184,
                            Jersey = (short)38,
                            Position = "C",
                            Sname = "Springer",
                            Weight = (short)71
                        },
                        new
                        {
                            PlayerId = "sullivar",
                            BirthCity = "Vancouver",
                            BirthState = "BC",
                            Birthday = new DateTime(2000, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Russel",
                            Height = (short)186,
                            Jersey = (short)39,
                            Position = "G",
                            Sname = "Sullivan",
                            Weight = (short)70
                        },
                        new
                        {
                            PlayerId = "travisj",
                            BirthCity = "Boston",
                            BirthState = "MA",
                            Birthday = new DateTime(2003, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "John",
                            Height = (short)200,
                            Jersey = (short)19,
                            Position = "C",
                            Sname = "Travis",
                            Weight = (short)74
                        },
                        new
                        {
                            PlayerId = "zauberz",
                            BirthCity = "Moosehead",
                            BirthState = "MA",
                            Birthday = new DateTime(1988, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fname = "Zeke",
                            Height = (short)203,
                            Jersey = (short)22,
                            Position = "RW",
                            Sname = "Zauber",
                            Weight = (short)74
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
