employees=Employees
name=Name
age=Age
salary=Salary
role=Role
creation=Creation time
analyst=is analyzing data in
designer=is designing using
developer=is coding in
manager=is managing a team of
members=members
writes=writes
autoTest=automating tests
manualTests=manual tests
